set(_CATKIN_CURRENT_PACKAGE "randomwalk")
set(randomwalk_MAINTAINER "towardthesea <ph17dn@gmail.com>")
set(randomwalk_DEPRECATED "")
set(randomwalk_VERSION "0.0.0")
set(randomwalk_BUILD_DEPENDS "roscpp" "geometry_msgs" "sensor_msgs")
set(randomwalk_RUN_DEPENDS "roscpp" "geometry_msgs" "sensor_msgs")
set(randomwalk_BUILDTOOL_DEPENDS "catkin")