set(_CATKIN_CURRENT_PACKAGE "playerros_teleop")
set(playerros_teleop_MAINTAINER "towardthesea <ph17dn@gmail.com>")
set(playerros_teleop_DEPRECATED "")
set(playerros_teleop_VERSION "0.0.0")
set(playerros_teleop_BUILD_DEPENDS "roscpp" "geometry_msgs")
set(playerros_teleop_RUN_DEPENDS "roscpp" "geometry_msgs")
set(playerros_teleop_BUILDTOOL_DEPENDS "catkin")